### ISSUE TITLE
Use Vector Drawable instead of different density tick marks

### ISSUE THREAD

**Issue by rakshakhegde** [badoualy/stepper-indicator#32]

**Comment by badoualy** [comment]
What are we talking about here with tick marks? You mean the circle for the current page?

**Comment by rakshakhegde** [comment]
Yes, though now I come to think of it, it's not all that important. Just nice to save a few bytes :)

**Comment by badoualy** [comment]
The circle of past step/current step is drawn via a Paint, the only use of drawable is for the "check" icon, indeed we could it for VectorDrawable, but I'm not sure it would save space since it would add the vector drawable support lib dependency right? So if it's not used in the final app, probably would in fact lose space :)
