### ISSUE TITLE
stpi_labels not working

### ISSUE THREAD

**Issue by CeRBeR666** [badoualy/stepper-indicator#37]
Hello I want try your class.  I couldn't run stpi_labels on layout
Help me ?

**Comment by Pabloku** [comment]
It is not working... any updates? 
Thanks!

**Comment by pouriabagheri** [comment]
it seems that there is no stpi_labels. maybe it's missing from the commit. @CeRBeR666 @Pabloku have you found a work around or solution ?

**Comment by pouriabagheri** [comment]
@CeRBeR666 @Pabloku if you haven't figured it out yet. this is happening because most probably you have used the  1.0.6 version which does not include the labels. and since there are no tags made for it yet you can't use jitpack neither. so i would suggest cloning the library and adding it as module locally.

**Comment by badoualy** [comment]
Sorry I have not much free time lately, and yes you can use jitpack without tags, the magic with jitpack is being able to use any commit as a maven library.
Use "master" as version name and you'll get the latest commit.

**Comment by pouriabagheri** [comment]
@badoualy I understand, thanks for the great library.

**Comment by badoualy** [comment]
A release will be made soon btw.
Closing issue as it should be resolved by using appropriate version.
