### ISSUE TITLE
Picking stepper colors from the app's theme

### ISSUE THREAD

**Issue by VioletGiraffe** [badoualy/stepper-indicator#6]
Wouldn't it be possible to apply theme colors to the stepper by default?

**Comment by badoualy** [comment]
Indeed, didn't think of that, will try to implement that this week end :)

**Comment by VioletGiraffe** [comment]
Great! And thanks for the awesome library. I'm not entirely sure yet if I'll manage to integrate in my app, but I sure hope so. Yours is by far the best Stepper implementation I've seen :)

**Comment by badoualy** [comment]
Thank you mate, 
I just implemented it, my friend https://dribbble.com/LeslyPyram designed it :)

Regarding the colors, I was thinking of using the colorPrimary instead of the default green, not sure if I should keep the grey or use the accent color instead for the second color? Not sure it would look good with accent color

**Comment by VioletGiraffe** [comment]
I'm thinking grey should stay, and either primary or accent color instead of green.

**Comment by badoualy** [comment]
``` gradle
compile 'com.github.badoualy:stepper-indicator:1.0.2'
```
